// Mocks generated by Mockito 5.4.2 from annotations
// in expense_manager/test/Backend/Appwrite_provider/set_selected.welltested_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:appwrite/models.dart' as _i3;
import 'package:expense_manager/Authentication/Auth_Provider/Auth_Provider.dart'
    as _i2;
import 'package:expense_manager/Backend/Appwrite_provider.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuth_State_0 extends _i1.SmartFake implements _i2.Auth_State {
  _FakeAuth_State_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocument_1 extends _i1.SmartFake implements _i3.Document {
  _FakeDocument_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [data_base].
///
/// See the documentation for Mockito's code generation for more information.
class Mockdata_base extends _i1.Mock implements _i4.data_base {
  Mockdata_base() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get selected => (super.noSuchMethod(
        Invocation.getter(#selected),
        returnValue: false,
      ) as bool);

  @override
  set selected(bool? _selected) => super.noSuchMethod(
        Invocation.setter(
          #selected,
          _selected,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Auth_State get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAuth_State_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.Auth_State);

  @override
  set state(_i2.Auth_State? _state) => super.noSuchMethod(
        Invocation.setter(
          #state,
          _state,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set expenses(List<_i3.Document>? _expenses) => super.noSuchMethod(
        Invocation.setter(
          #expenses,
          _expenses,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Document get deleted_document => (super.noSuchMethod(
        Invocation.getter(#deleted_document),
        returnValue: _FakeDocument_1(
          this,
          Invocation.getter(#deleted_document),
        ),
      ) as _i3.Document);

  @override
  set deleted_document(_i3.Document? _deleted_document) => super.noSuchMethod(
        Invocation.setter(
          #deleted_document,
          _deleted_document,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void set_selected(bool? TF) => super.noSuchMethod(
        Invocation.method(
          #set_selected,
          [TF],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> addData({
    required String? reason,
    required double? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addData,
          [],
          {
            #reason: reason,
            #amount: amount,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<dynamic> getData() => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> Delete_Document(String? DocId) => (super.noSuchMethod(
        Invocation.method(
          #Delete_Document,
          [DocId],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> Update_Document() => (super.noSuchMethod(
        Invocation.method(
          #Update_Document,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
